services:
  - type: web
    name: store-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --run-syncdb --verbosity 2
    startCommand: gunicorn config.wsgi
